### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by maxsombra** [berak/uniform-lbp#1]
hi

Im all the clasifiers have update

**Comment by berak** [comment]
hi, @maxsombra , no only those, which inherit from 'ClassifierNearest' , so: CL_NORM_L1, CL_NORM_L2, CL_HIST_CHI_CL_HIST_HELL, CL_KLDIV . (forgot to implement it for KNN, btw)

again, this is more an experimenting platform, not so much a production framework

**Comment by maxsombra** [comment]
hi thanks
I'm doing an application for my work, i try to improve my classifier with machine learning but i need update, in the moment i use COMP BHATTACHARYYA and cosine differences.

you have any idea for me

thanks again

**Comment by berak** [comment]
sorry, i forgot them in my list, - both cosine and BHATTACHARYYA classifiers can be updated, too.

anything else, i can do ? can we close this ?
