### ISSUE TITLE
ClassifierSvmMulti::predict issue

### ISSUE THREAD

**Issue by rmekdma** [berak/uniform-lbp#2]
Hi, I found something strange in the ClassifierSvmMulti::predict() function.
At line 280, the predicted labels are being compared.

```
if (p > m)
```

Did you mean to produce raw output like this?

```
svms[j]->predict(query, r, ml::StatModel::RAW_OUTPUT)
```

If then, how about accumulating raw outputs and return the class label of the largest output?

**Comment by berak** [comment]
oh, thanks for your feedback ! 

"the predicted labels are being compared." - yes, that's kinda sloppy. the labels are only -1,1 anyway, so we could even just take the 1st positive item and be done.

"Did you mean to produce raw output like this" - that's a nice idea. i'm just not sure, if the largest raw output translates to the best prediction (will have to look this up further).

**Comment by rmekdma** [comment]
Thanks! I didn't recall that the possible outputs are -1 and 1. 
Also I expect that the raw result will be positive for label -1 and negative for label 1. (positive value for smaller index). So if you are going to use the raw output in ClassifierSvmMulti class, consider using it only when the value is negative.

**Comment by berak** [comment]
"Also I expect that the raw result will be positive for label -1 and negative for label 1" - yes, that's what i'm seeing here. so, we want the (absolute)smallest negative value ? (in case there are multiple positive responses)

(i just tried that, - no real improvement, unfortunately)

**Comment by rmekdma** [comment]
Yes, I think the label with the samllest negative value will be the answer. If the smallest value is positive... I think you can return the label with smallest value (which is practical) or negative label to give not-found information (which is more correct). 

The changes to code may be easy. I changed it like this (not tested)

```
    for (size_t j=0; j<svms.size(); ++j)
    {
        Mat r;
        svms[j]->predict(query, r, ml::StatModel::RAW_OUTPUT);
        float p = r.at<float>(0);
        if (p < m)
        {
            m = p;
            mi = float(j);
        }

    }
```

PS: The raw output will be helpful if many values are accumulated. Anyway, not this case ;)

**Comment by berak** [comment]
thanks for the idea, nonetheless !
